export const ROLES = {
  ADMIN: "Admin",
  MANAGER: "Manager",
  EMPLOYEE: "Employee",
};

export const PERMISSIONS = {
  APPLY_DISCOUNT: [ROLES.ADMIN],

  REFUND_ORDER: [ROLES.ADMIN, ROLES.MANAGER],

  MANAGE_PRODUCTS: [ROLES.ADMIN],

  MANAGE_USERS: [ROLES.ADMIN],

  MANAGE_INVENTORY: [ROLES.ADMIN, ROLES.MANAGER],
};
